# Large-scale configuration for enhanced RL system comprehensive experiments
# Graph configuration - large graph for extensive analysis
graph:
  num_nodes: 100  # Large number of nodes for real-world scale testing (reduced for stability)
  edge_probability: 0.25  # Balanced density for complex graphs
  weight_range: [0.1, 1.0]

# Partitioning strategy configuration - optimized for quality
partition:
  num_partitions: 4  # More partitions for complex analysis
  balance_weight: 0.4
  cut_size_weight: 0.4
  conductance_weight: 0.2
  use_laplacian: true
  min_partition_size: 15
  max_partition_size: 35
  balance_threshold: 0.8  # Achievable balance requirement
  conductance_threshold: 0.3  # Achievable conductance requirement
  use_hybrid_strategy: false  # Use simple strategy for testing
  strategy_weights: [0.4, 0.3, 0.3]
  epsilon_decay: 0.995  # Moderate decay for exploration

# Agent configuration - enhanced settings compatible with our system
agent:
  # Training parameters - optimized for enhanced features
  learning_rate: 0.005  # Higher learning rate for faster convergence on large graphs
  epsilon: 0.1
  epsilon_start: 1.0
  epsilon_end: 0.01  # Reasonable end epsilon
  epsilon_decay: 0.995  # Moderate decay
  gamma: 0.99  # Standard discount factor
  memory_size: 50000  # Large memory for experience replay
  batch_size: 64  # Stable batch size
  target_update: 50  # More frequent updates for large graphs
  # Enhanced features for our system
  use_attention: true  # Enable attention mechanisms
  num_heads: 4  # Multi-head attention
  dropout: 0.1  # Dropout for regularization
  lr_step_size: 50  # More frequent LR scheduling
  lr_gamma: 0.95  # Less aggressive LR decay
  balance_weight: 0.5  # Enhanced reward weighting
  density_weight: 0.5  # Enhanced reward weighting
  # Neural network dimensions - enhanced for our system
  feature_dim: 128  # Enhanced feature dimensions
  state_dim: 64  # Enhanced state representation
  hidden_layers: [256, 256, 128]  # Deep architecture

# System configuration - enhanced episodes for comprehensive learning
system:
  num_episodes: 500  # Moderate number for better performance monitoring
  max_steps: 50  # Moderate steps per episode for thorough exploration
  log_interval: 25  # More frequent logging for monitoring
  seed: 42
  log_level: "INFO"

# Testing configuration
test:
  num_runs: 1  # Single run for initial testing
